# Generated by Django 2.2.6 on 2020-11-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='', max_length=30)),
                ('total', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='register_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=30)),
                ('place', models.CharField(default='', max_length=30)),
                ('mobile_Number', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='unit_register_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=30)),
                ('place', models.CharField(default='', max_length=30)),
                ('capacity', models.CharField(default='', max_length=30)),
                ('mobile_Number', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='workers_register_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=30)),
                ('dob', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=30)),
                ('place', models.CharField(default='', max_length=30)),
                ('mobile_Number', models.CharField(default='', max_length=30)),
                ('workers_type', models.CharField(default='0', max_length=30)),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.unit_register_tb')),
            ],
        ),
        migrations.CreateModel(
            name='waste_location_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=30)),
                ('place', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=30)),
                ('worker_email', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.register_tb')),
            ],
        ),
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('code', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=290)),
                ('image', models.ImageField(upload_to='files')),
                ('price', models.CharField(default='', max_length=30)),
                ('quantity', models.CharField(default='', max_length=30)),
                ('unitid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.unit_register_tb')),
            ],
        ),
        migrations.CreateModel(
            name='order_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=30)),
                ('payment', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=30)),
                ('payment_status', models.CharField(default='', max_length=30)),
                ('worker_email', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('cart_id', models.CharField(default='', max_length=30)),
                ('unit_id', models.CharField(default='', max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.register_tb')),
            ],
        ),
        migrations.CreateModel(
            name='order_item_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('payment_status', models.CharField(default='', max_length=30)),
                ('worker_email', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.cart_tb')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.order_tb')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.product_tb')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.unit_register_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.register_tb')),
            ],
        ),
        migrations.AddField(
            model_name='cart_tb',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.product_tb'),
        ),
        migrations.AddField(
            model_name='cart_tb',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.unit_register_tb'),
        ),
        migrations.AddField(
            model_name='cart_tb',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.register_tb'),
        ),
    ]
