# Generated by Django 2.2.6 on 2020-11-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycling_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default='', max_length=30)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.product_tb')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.unit_register_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling_app.register_tb')),
            ],
        ),
    ]
