# Generated by Django 2.2.6 on 2020-11-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycling_app', '0002_feedback_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_tb',
            name='worker_email',
        ),
    ]
