# Generated by Django 3.1.5 on 2021-01-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling_app', '0003_remove_order_tb_worker_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_tb',
            name='Aadhar_Number',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='workers_register_tb',
            name='Aadhar_Number',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
