# Generated by Django 3.1.5 on 2021-01-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling_app', '0004_auto_20210127_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_register_tb',
            name='licence_number',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
