# Generated by Django 5.2 on 2026-10-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling_app', '0006_alter_cart_tb_id_alter_feedback_tb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_location_tb',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waste_location_tb',
            name='ai_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='waste_location_tb',
            name='ai_recyclable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waste_location_tb',
            name='ai_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waste_location_tb',
            name='ai_waste_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='waste_location_tb',
            name='waste_image',
            field=models.ImageField(blank=True, null=True, upload_to='waste_images/'),
        ),
    ]
