# Generated by Django 5.2 on 2026-10-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling_app', '0007_waste_location_tb_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_register_tb',
            name='accepted_waste_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='unit_register_tb',
            name='available_capacity_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='unit_register_tb',
            name='district',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='unit_register_tb',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
