# Generated by Django 5.2 on 2026-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling_app', '0008_unit_register_tb_accepted_waste_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_location_tb',
            name='waste_quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
