# Generated by Django 5.2 on 2026-10-09 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling_app', '0009_waste_location_tb_waste_quantity_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_location_tb',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waste_location_tb',
            name='assigned_recycler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_waste_reports', to='recycling_app.unit_register_tb'),
        ),
    ]
